"""
    This contain all the loss functions thare are used to find error gradient from model predictions.
    Loss functions can further be divided into two type of loss functions
    
    * Classification loss - Loss functions that calculate error gradient for classification task such as BCE
    * Regression loss - Calculates the difference between true and predicted values generated by model such as MAE or MSE
    
    Common loss functions that are implemeneted...
    
    * Regression Loss
        1. Mean Absolute Error
        2. Mean Squared Error

    * Classification Loss
        1. Binary Crss Entropy (BCE)
        2. Categorical Cross Entropy (Multi-Log-Loss)

    All loss function follows a similar structure to class Layer.
    forward() method calculates the loss.
    backward() method triggers the backpropogation.
"""
import numpy as np
from core.layers import Layer

# Base class for loss function
class Loss:
    def __init__(self):
        self.output_gradient = None
        self.y_preds, self.y_true = None, None

    def forward(self, y_preds : np.ndarray, y_true : np.ndarray):
        raise NotImplementedError("Forward method must be overriden.")

    def backward(self, model : Layer):
        raise NotImplementedError("Backward method must be overriden")
    
    def __call__(self, y_preds : np.ndarray, y_true : np.ndarray):
        self.y_preds, self.y_true = y_preds, y_true
        self.output_grad =  self.forward()
        return self.output_grad

# Mean Absolute Error
class MAE(Loss):
    def forward(self):
        return np.mean(np.abs(self.y_preds - self.y_true))
    
    def backward(self, model : Layer):
        return model.backward(np.sign(self.y_preds - self.y_true) / self.y_preds.shape[0])

# Mean Squared Error
class MSE(Loss):

    def forward(self):
        return np.mean(2 * (self.y_preds - self.y_true))

    def backward(self, model : Layer):
        return model.backward((2 * (self.y_preds - self.y_true)) / self.y_true.shape[0])

# Binary Cross Entropy
class BCE(Loss):

    def forward(self):
        return np.mean(-(self.y_true * np.log(self.y_true) + ((1 - self.y_true) * np.log(1 - self.y_preds))))
    
    def backward(self, model : Layer):
        return model.backward(-(self.y_true * np.log(self.y_true) + ((1 - self.y_true) * np.log(1 - self.y_preds)) / self.y_true.shape[0]))

# Categorical Cross Entropy
class CCE(Loss):

    def forward(self):
        return -np.mean(np.sum(self.y_true * np.log(self.y_preds), axis=-1))

    def backward(self, model : Layer):
        return model.backward(-np.sum(self.y_true * np.log(self.y_preds)) / self.y_true.shape[0])


